symbs = dict([["a","первый"],["b","второй"]])
more_symbs = dict([["c","третий"],["d","четвертый"]])
symbs.update(more_symbs)
print("Словарь",symbs)
print("Количество ключей в словаре",len(symbs))
print("Элемент с ключем 'с':",symbs.get("c","нет такого ключа!"))
print("Наличие элемента с ключем 'c':","c" in symbs)
del symbs["c"]
print("Словарь",symbs)
print("Элемент с ключем 'с':",symbs.get("c","нет такого ключа!"))
print("Наличие элемента с ключем 'c':","c" in symbs)
print("Ключи словаря:",list(symbs.keys()))
print("Ключи словаря",list(symbs.values()))
print("Удаляетсяс элемент со значением: ",symbs.pop("b"))
print("Словарь",symbs)
symbs.clear()
print("Словарь",symbs)
